FROM alpine:latest
RUN apk update
RUN apk add --no-cache openssh zstd mercurial wireguard-tools libc6-compat coreutils tar
RUN apk add build-base curl make git linux-headers openssl-dev pkgconf m4 mercurial zlib-dev keyutils-dev libssh2-dev libtool autoconf automake gcc libgccjit-dev texinfo libsndfile-dev meson
RUN mkdir /usr/local/include