FROM localhost/w3:latest
ARG WEB_USER=web
ARG WEB_HOME=/home/${WEB_USER}
ARG WEB_ID=840
USER root
RUN --network=host apk add go
RUN addgroup -g 840 web
RUN adduser -D -u ${WEB_ID} -G web ${WEB_USER}
USER root
WORKDIR /usr/src/infra
RUN skel build caddy 
RUN skel install caddy
RUN skel clean
USER ${WEB_USER}
WORKDIR ${WEB_HOME}
RUN mkdir -p ${WEB_HOME}/.stash ${WEB_HOME}/www
ENV WEB_ID=${WEB_ID}
ENV WEB_USER=${WEB_USER}
CMD ["run", "-c", "caddy.json"]
ENTRYPOINT ["caddy"]
EXPOSE 2020 8080 8443