FROM localhost/alpine:latest
ARG WORKER_ID=908
ARG WORKER=worker
ARG WORKER_HOME=/home/${WORKER}
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf m4 mercurial llvm
RUN mkdir -pv /usr/share/lisp /usr/local/share/lisp
RUN addgroup -g 128 engineer
RUN addgroup -g 256 operator
RUN addgroup -g 512 worker
RUN adduser -D -u ${WORKER_ID} -G worker ${WORKER}
RUN chown -R ${WORKER_ID}:worker /usr/local/
RUN mkdir -pv ${WORKER_HOME}/.stash
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
ENV PATH="$PATH:/usr/local/share/cargo/bin:/usr/local/share/lisp/bin"
# RUN ./bootstrap.sh
# WORKDIR ${WORKER_HOME}
# RUN rm -rf /usr/local/src/*
USER ${WORKER}
ENV WORKER=${WORKER}
ENV WORKER_ID=${WORKER_ID}
ENV WORKER_HOME=${WORKER_HOME}
ENTRYPOINT ["sh"]