FROM localhost/w0:latest
ARG VC_USER=vc
ARG VC_HOME=/home/${VC_USER}
ARG VC_ID=842
USER root
RUN apk add py3-pygments py3-pygit2 py3-dulwich py3-pip apache2-utils uwsgi
RUN addgroup ${VC_USER}
RUN adduser -G vc -S -s /usr/bin/bash -u ${VC_ID} ${VC_USER}
USER ${VC_USER}
WORKDIR ${VC_HOME}
RUN pip install --user --break-system-packages hg-evolve 
ENV VC_USER=${VC_USER}
ENV VC_ID=${VC_ID}
CMD ["./serve.sh"]