FROM localhost/archlinux:latest
RUN --network=host pacman -Sy uutils-coreutils sysstat iotop imagemagick giflib libgccjit libxaw snappy sbcl clang lld liburing libxkbcommon --noconfirm
# custom
ARG DEV=dev
ARG DEV_HOME=/home/${DEV}
ARG ID=808
# stage0
RUN mkdir -p /usr/share/lisp /usr/local/share/lisp /usr/local/share/rust
COPY .stash/bin/ /usr/local/bin/
COPY .stash/lib/ /usr/local/lib/
COPY .stash/include/ /usr/local/include/
COPY .stash/share/ /usr/local/share/
COPY .stash/src/ /usr/local/src/
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/rust/cargo"
ENV RUSTUP_HOME="/usr/local/share/rust/rustup"
# stage1
ENV PATH="$PATH:/usr/local/share/rust/cargo/bin"
RUN skel make rustup
RUN rustup default nightly
RUN rustup component add --toolchain nightly rust-src rust-analyzer rustc-dev llvm-tools-preview
RUN skel make tree-sitter
RUN skel make tree-sitter-langs
RUN useradd --system -s /usr/bin/bash -u ${ID} -k /etc/skel -m ${DEV}
RUN groupadd -g 128 engineer -U ${DEV}
RUN groupadd -g 256 operator -U ${DEV}
RUN chown -R ${DEV}:engineer /usr/local/share/
RUN chown -R ${DEV}:engineer /usr/local/src/
RUN chown -R ${DEV}:engineer /usr/local/bin/
RUN chown -R ${DEV}:engineer /usr/local/etc/
RUN chown -R ${DEV}:engineer /usr/local/man/
USER ${DEV}
RUN mkdir ${DEV_HOME}/.stash
RUN skel make quicklisp
RUN skel make clean
WORKDIR ${DEV_HOME}
ENV DEV=${DEV}
ENV DEV_ID=${ID}