FROM localhost/dev:latest
USER root
RUN usermod -l operator --move-home --home /home/operator ${DEV}
RUN echo "operator ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/operator
RUN --network=host pacman -Sy aspell hunspell-en_us --noconfirm
USER operator
WORKDIR /home/operator
RUN hg clone https://vc.compiler.company/comp/infra .stash/infra
RUN .stash/infra/scripts/wg-gen-keys.sh private.key public.key
WORKDIR .stash/infra
# RUN sudo skel run install-emacs-pack
RUN sudo skel clean
WORKDIR /home/operator
RUN cd .stash/home && hg up operator && homer install
ENV DEV=operator
ENV DEV_HOME=/home/operator