FROM fedora:latest
RUN dnf install -y mercurial git openssh wireguard-tools tar libzstd-devel curl make openssl zlib keyutils-libs-devel libssh2-devel gcc gcc-c++ libxkbcommon-devel btrfs-progs-devel snappy-devel gflags-devel bzip2-devel
# update liburing (need at least 2.9)
RUN git clone https://github.com/axboe/liburing
WORKDIR /liburing
RUN ./configure --cc=gcc --cxx=g++
RUN make -j$(nproc)
RUN make liburing.pc
RUN make install
RUN rm -rf /liburing
WORKDIR /