FROM alpine:latest
RUN apk update
RUN apk add --no-cache openssh mercurial wireguard-tools liburing libc6-compat coreutils tar
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf m4 mercurial zlib-dev keyutils-dev libssh2-dev libtool autoconf automake gcc libgccjit-dev texinfo alsa-lib-dev libsndfile-dev meson
WORKDIR /