FROM localhost/archlinux:latest
RUN --network=host pacman -Sy uutils-coreutils sysstat iotop imagemagick giflib libgccjit libxaw snappy sbcl liburing libxkbcommon --noconfirm
# custom
ARG DEV=dev
ARG DEV_HOME=/home/${DEV}
ARG ID=808
# stage0
RUN mkdir -p /usr/share/lisp /usr/local/share/lisp
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/core
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
# stage1
RUN ./bootstrap.sh
ENV PATH="$PATH:/usr/local/share/cargo/bin"
RUN .stash/bin/sk make rustup
RUN rustup update
# dev rustc components
RUN rustup default nightly
RUN rustup component add --toolchain nightly rust-src rust-analyzer rustc-dev llvm-tools-preview
RUN .stash/bin/sk make sbcl
RUN .stash/bin/sk make quicklisp
RUN .stash/bin/sk make sbcl-install
RUN .stash/bin/sk make tree-sitter
RUN .stash/bin/sk make tree-sitter-langs
RUN .stash/bin/sk make emacs-mini
RUN .stash/bin/sk make emacs-install
RUN .stash/bin/sk make rocksdb
RUN .stash/bin/sk make rocksdb-install
#ADD etc/sbclrc /etc/sbclrc
#COPY etc/skel/ /etc/skel/
#ADD etc/shells /etc/
RUN useradd --system -s /usr/bin/bash -u ${ID} -k /etc/skel -m ${DEV}
RUN groupadd -g 128 engineer -U ${DEV}
RUN groupadd -g 256 operator -U ${DEV}
# RUN make core-install
WORKDIR /usr/local/src
RUN cp -rf core/lisp /usr/local/share/lisp/core
RUN rm -rf ./*
RUN chown -R ${DEV}:engineer /usr/local/share/
RUN chown -R ${DEV}:engineer /usr/local/src/
RUN chown -R ${DEV}:engineer /usr/local/bin/
RUN chown -R ${DEV}:engineer /usr/local/etc/
RUN chown -R ${DEV}:engineer /usr/local/man/
USER ${DEV}
WORKDIR ${DEV_HOME}
RUN hg clone https://vc.compiler.company/comp/infra
RUN hg clone https://vc.compiler.company/comp/core
ENV DEV=${DEV}
ENV DEV_ID=${ID}