FROM localhost/archlinux:latest
RUN --network=host pacman -Sy uutils-coreutils sysstat iotop imagemagick giflib libgccjit libxaw snappy llvm clang lld liburing libxkbcommon numactl --noconfirm
ARG VC_UPSTREAM=https:/vc.localhost
RUN mkdir -p /usr/share/lisp /usr/local/share/lisp /usr/local/share/rust /opt/store /opt/stash
RUN ssh-keygen -A
RUN pacman -Scc --noconfirm
RUN hg clone https://vc.localhost/infra
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/rust/cargo"
ENV RUSTUP_HOME="/usr/local/share/rust/rustup"
RUN ./bootstrap.sh
RUN mv .stash/bin/core /usr/local/bin/core
RUN ln -sf /usr/local/bin/core /usr/local/bin/skel
RUN ln -sf /usr/local/bin/core /usr/local/bin/homer
ENV PATH="$PATH:/usr/local/share/rust/cargo/bin"
RUN ./scripts/install-rocksdb-pack.sh
RUN skel build tree-sitter
RUN skel install tree-sitter tree-sitter-langs
RUN mv .stash/lib/** /usr/local/lib/
RUN mv .stash/share/lisp/** /usr/local/share/lisp/
RUN mv .stash/bin/* /usr/local/bin/
RUN skel install quicklisp
RUN skel install rustup
RUN rustup default nightly
RUN rustup component add --toolchain nightly rust-src rust-analyzer rustc-dev llvm-tools-preview
ENTRYPOINT ["/usr/bin/bash"]