FROM localhost/alpine:latest
# VOLUME /opt/store
# VOLUME /opt/stash
ARG ID=908
ARG WORKER=worker
ARG WORKER_HOME=/home/${WORKER}
# TODO: build sbcl for musl
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf clang m4
RUN mkdir -p /usr/share/lisp /usr/local/share/lisp
COPY .stash/bin/ /usr/local/bin/
COPY .stash/lib/ /usr/local/lib/
COPY .stash/include/ /usr/local/include/
COPY .stash/share/ /usr/local/share/
COPY .stash/src/ /usr/local/src/
WORKDIR /usr/local/src
RUN hg clone https://vc.compiler.company/comp/infra
WORKDIR infra
# RUN scripts/get-sk.sh
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
ENV PATH="$PATH:/usr/local/share/cargo/bin:/usr/local/share/lisp/bin"
RUN adduser -D -u ${ID} -k /etc/skel ${WORKER}
USER ${WORKER}
WORKDIR ${WORKER_HOME}
ENV WORKER=${WORKER}
ENV WORKER_ID=${ID}
ENV WORKER_HOME=${WORKER_HOME}
ENTRYPOINT ["sh"]