FROM localhost/alpine:latest
RUN apk add --no-cache build-base zstd-dev git make linux-headers pkgconf m4 perl autoconf texinfo ncurses-dev libgccjit-dev zlib-dev tar shared-mime-info tree-sitter-dev btrfs-progs-dev liburing-dev curl alsa-lib-dev libssh2-dev clang lld musl-dev openssh libxkbcommon-dev sbcl
RUN hg clone https://vc.compiler.company/infra
WORKDIR infra
RUN ./check.sh
RUN mkdir -pv .stash/src .stash/tmp
RUN ./scripts/install-rocksdb-pack.sh x86_64-unknown-linux-musl
# RUN ./scripts/install-sbcl-pack.sh x86_64-unknown-linux-musl
RUN ./scripts/install-core-pack.sh x86_64-unknown-linux-musl
RUN ssh-keygen -A
RUN skel clean