FROM localhost/alpine:latest
RUN apk add build-base zstd-dev curl make git linux-headers openssl-dev pkgconf m4 mercurial llvm libgccjit-dev zlib-dev texinfo gnutls-dev ncurses-dev
RUN mkdir -pv /usr/share/lisp /usr/local/share/lisp
RUN hg clone https://vc.compiler.company/comp/infra
WORKDIR infra
ENV CARGO_HOME="/usr/local/share/cargo"
ENV RUSTUP_HOME="/usr/local/share/rustup"
ENV PATH="$PATH:/usr/local/share/cargo/bin:/usr/local/share/lisp/bin"
RUN mkdir -pv .stash/tmp
# RUN ./scripts/install-emacs-mini-pack.sh x86_64-unknown-linux-musl # fails byte-code validation
# RUN ./scripts/install-sbcl-pack.sh x86_64-unknown-linux-musl
# RUN ./scripts/install-rocksdb-pack.sh x86_64-unknown-linux-musl
RUN cd .stash && curl -O https://beta.quicklisp.org/quicklisp.lisp
RUN ./scripts/quicklisp-install.sh
# RUN ./bootstrap.sh
ENTRYPOINT ["sh"]