FROM archlinux:latest
RUN --network=host pacman-key --init
RUN --network=host pacman-key --populate archlinux
RUN --network=host pacman -Syu base-devel less uutils-coreutils openssl openssh mercurial git liburing wireguard-tools libxcb zstd --noconfirm